# Generated by Django 2.2.4 on 2021-05-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auther',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
